---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
<<<<<<< HEAD
=======

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
>>>>>>> dacf787... message
