FROM httpd:latest
COPY assets/ /usr/local/apache2/htdocs/assets/
COPY fonts/ /usr/local/apache2/htdocs/fonts/
COPY icons/ /usr/local/apache2/htdocs/icons/
COPY img/ /usr/local/apache2/htdocs/img/
COPY moment/ /usr/local/apache2/htdocs/moment/
COPY crossdomain.xml /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/
COPY robots.txt /usr/local/apache2/htdocs/