version: '2'
services:
  barber-db:
    image: mysql:latest
    volumes:
      - ./db/:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: repgate
      #MYSQL_DATABASE: nova
      MYSQL_USER: barber
      MYSQL_PASSWORD: repgate
  barber:
    depends_on:
      - barber-db
    image: novaservice/barber-service:latest
    ports:
      - "8080:8080" #порт сервака, слева наружу, справа от контейнера
    restart: always
    environment:
      DB_URL: barber-db:3306/nova?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Moscow&useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASS: repgate
